### ISSUE TITLE
Use "Lato" as font-family

### ISSUE THREAD

**Issue by johnLexicon** [Mikael-Helin/FE22_Casino#5]
I think the site would look really great if we used the **"Lato" font type** as the font-family.
The font type is free and available on:
https://fonts.google.com/specimen/Lato#standard-styles

I was thinking that we can import the styles:
**Light 300
Light 300 Italic
Regular  400
Bold 700**

If we need more styles we can just add them to the import later on.
Steps:
1. Create a CSS file called main.css
2. Import the font type in the main.css file (follow instructions from the Google fonts site if needed)
3. Create a CSS-rule for the body element and add the the **Lato** font type as the value for the font-family.
4. Use **sans-serif** as a backup if something goes wrong when importing the Lato font type.
5. Link the created main.css file into the html pages index, exchange, register.

**Comment by itaxudata** [comment]
Hej @johnLexicon. Har gjort ändringar enligt issue #5, se commit 9b0691e5992d63e891b8aa4133aa6f3fd01dc369 så det inte är helgalet :-)

**Comment by johnLexicon** [comment]
Tack @adam-aksu , det var precis det jag menade med issue #5.
Har nu mergat din branch med main branchen och pushat upp ändringarna till GitHub.
Tack Adam
